// NIOS2_WEEK2.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module NIOS2_WEEK2 (
		inout  wire        accel_I2C_SDAT,      //          accel.I2C_SDAT
		output wire        accel_I2C_SCLK,      //               .I2C_SCLK
		output wire        accel_G_SENSOR_CS_N, //               .G_SENSOR_CS_N
		input  wire        accel_G_SENSOR_INT,  //               .G_SENSOR_INT
		input  wire        camera_ready_export, //   camera_ready.export
		input  wire        clk_clk,             //            clk.clk
		output wire [12:0] dram_addr,           //           dram.addr
		output wire [1:0]  dram_ba,             //               .ba
		output wire        dram_cas_n,          //               .cas_n
		output wire        dram_cke,            //               .cke
		output wire        dram_cs_n,           //               .cs_n
		inout  wire [15:0] dram_dq,             //               .dq
		output wire [1:0]  dram_dqm,            //               .dqm
		output wire        dram_ras_n,          //               .ras_n
		output wire        dram_we_n,           //               .we_n
		output wire        gpio_export,         //           gpio.export
		output wire [16:0] img_addr_export,     //       img_addr.export
		input  wire        key1_export,         //           key1.export
		input  wire        key2_export,         //           key2.export
		output wire [9:0]  led_export,          //            led.export
		output wire [3:0]  pixel_export,        //          pixel.export
		output wire [7:0]  seven_seg_0_export,  //    seven_seg_0.export
		output wire [7:0]  seven_seg_1_export,  //    seven_seg_1.export
		output wire [7:0]  seven_seg_2_export,  //    seven_seg_2.export
		output wire [7:0]  seven_seg_3_export,  //    seven_seg_3.export
		output wire [7:0]  seven_seg_4_export,  //    seven_seg_4.export
		output wire [7:0]  seven_seg_5_export,  //    seven_seg_5.export
		input  wire        spi_peripheral_MISO, // spi_peripheral.MISO
		output wire        spi_peripheral_MOSI, //               .MOSI
		output wire        spi_peripheral_SCLK, //               .SCLK
		output wire        spi_peripheral_SS_n, //               .SS_n
		output wire        wren_export          //           wren.export
	);

	wire         nios2_gen2_0_debug_reset_request_reset;                                      // nios2_gen2_0:debug_reset_request -> [rst_controller:reset_in0, rst_controller:reset_in1, rst_controller_001:reset_in0]
	wire  [31:0] nios2_gen2_0_data_master_readdata;                                           // mm_interconnect_0:nios2_gen2_0_data_master_readdata -> nios2_gen2_0:d_readdata
	wire         nios2_gen2_0_data_master_waitrequest;                                        // mm_interconnect_0:nios2_gen2_0_data_master_waitrequest -> nios2_gen2_0:d_waitrequest
	wire         nios2_gen2_0_data_master_debugaccess;                                        // nios2_gen2_0:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:nios2_gen2_0_data_master_debugaccess
	wire  [26:0] nios2_gen2_0_data_master_address;                                            // nios2_gen2_0:d_address -> mm_interconnect_0:nios2_gen2_0_data_master_address
	wire   [3:0] nios2_gen2_0_data_master_byteenable;                                         // nios2_gen2_0:d_byteenable -> mm_interconnect_0:nios2_gen2_0_data_master_byteenable
	wire         nios2_gen2_0_data_master_read;                                               // nios2_gen2_0:d_read -> mm_interconnect_0:nios2_gen2_0_data_master_read
	wire         nios2_gen2_0_data_master_write;                                              // nios2_gen2_0:d_write -> mm_interconnect_0:nios2_gen2_0_data_master_write
	wire  [31:0] nios2_gen2_0_data_master_writedata;                                          // nios2_gen2_0:d_writedata -> mm_interconnect_0:nios2_gen2_0_data_master_writedata
	wire  [31:0] nios2_gen2_0_instruction_master_readdata;                                    // mm_interconnect_0:nios2_gen2_0_instruction_master_readdata -> nios2_gen2_0:i_readdata
	wire         nios2_gen2_0_instruction_master_waitrequest;                                 // mm_interconnect_0:nios2_gen2_0_instruction_master_waitrequest -> nios2_gen2_0:i_waitrequest
	wire  [26:0] nios2_gen2_0_instruction_master_address;                                     // nios2_gen2_0:i_address -> mm_interconnect_0:nios2_gen2_0_instruction_master_address
	wire         nios2_gen2_0_instruction_master_read;                                        // nios2_gen2_0:i_read -> mm_interconnect_0:nios2_gen2_0_instruction_master_read
	wire   [7:0] mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_readdata;    // ACCEL_SPI:readdata -> mm_interconnect_0:ACCEL_SPI_avalon_accelerometer_spi_mode_slave_readdata
	wire         mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_waitrequest; // ACCEL_SPI:waitrequest -> mm_interconnect_0:ACCEL_SPI_avalon_accelerometer_spi_mode_slave_waitrequest
	wire   [0:0] mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_address;     // mm_interconnect_0:ACCEL_SPI_avalon_accelerometer_spi_mode_slave_address -> ACCEL_SPI:address
	wire         mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_read;        // mm_interconnect_0:ACCEL_SPI_avalon_accelerometer_spi_mode_slave_read -> ACCEL_SPI:read
	wire   [0:0] mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_byteenable;  // mm_interconnect_0:ACCEL_SPI_avalon_accelerometer_spi_mode_slave_byteenable -> ACCEL_SPI:byteenable
	wire         mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_write;       // mm_interconnect_0:ACCEL_SPI_avalon_accelerometer_spi_mode_slave_write -> ACCEL_SPI:write
	wire   [7:0] mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_writedata;   // mm_interconnect_0:ACCEL_SPI_avalon_accelerometer_spi_mode_slave_writedata -> ACCEL_SPI:writedata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect;                  // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_chipselect -> jtag_uart_0:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata;                    // jtag_uart_0:av_readdata -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest;                 // jtag_uart_0:av_waitrequest -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address;                     // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_address -> jtag_uart_0:av_address
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read;                        // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_read -> jtag_uart_0:av_read_n
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write;                       // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_write -> jtag_uart_0:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata;                   // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_writedata -> jtag_uart_0:av_writedata
	wire  [31:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata;                     // nios2_gen2_0:debug_mem_slave_readdata -> mm_interconnect_0:nios2_gen2_0_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest;                  // nios2_gen2_0:debug_mem_slave_waitrequest -> mm_interconnect_0:nios2_gen2_0_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess;                  // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_debugaccess -> nios2_gen2_0:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address;                      // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_address -> nios2_gen2_0:debug_mem_slave_address
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read;                         // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_read -> nios2_gen2_0:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable;                   // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_byteenable -> nios2_gen2_0:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write;                        // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_write -> nios2_gen2_0:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata;                    // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_writedata -> nios2_gen2_0:debug_mem_slave_writedata
	wire         mm_interconnect_0_ledr_s1_chipselect;                                        // mm_interconnect_0:LEDR_s1_chipselect -> LEDR:chipselect
	wire  [31:0] mm_interconnect_0_ledr_s1_readdata;                                          // LEDR:readdata -> mm_interconnect_0:LEDR_s1_readdata
	wire   [1:0] mm_interconnect_0_ledr_s1_address;                                           // mm_interconnect_0:LEDR_s1_address -> LEDR:address
	wire         mm_interconnect_0_ledr_s1_write;                                             // mm_interconnect_0:LEDR_s1_write -> LEDR:write_n
	wire  [31:0] mm_interconnect_0_ledr_s1_writedata;                                         // mm_interconnect_0:LEDR_s1_writedata -> LEDR:writedata
	wire         mm_interconnect_0_sram_s1_chipselect;                                        // mm_interconnect_0:SRAM_s1_chipselect -> SRAM:chipselect
	wire  [31:0] mm_interconnect_0_sram_s1_readdata;                                          // SRAM:readdata -> mm_interconnect_0:SRAM_s1_readdata
	wire  [11:0] mm_interconnect_0_sram_s1_address;                                           // mm_interconnect_0:SRAM_s1_address -> SRAM:address
	wire   [3:0] mm_interconnect_0_sram_s1_byteenable;                                        // mm_interconnect_0:SRAM_s1_byteenable -> SRAM:byteenable
	wire         mm_interconnect_0_sram_s1_write;                                             // mm_interconnect_0:SRAM_s1_write -> SRAM:write
	wire  [31:0] mm_interconnect_0_sram_s1_writedata;                                         // mm_interconnect_0:SRAM_s1_writedata -> SRAM:writedata
	wire         mm_interconnect_0_sram_s1_clken;                                             // mm_interconnect_0:SRAM_s1_clken -> SRAM:clken
	wire         mm_interconnect_0_gpio3_s1_chipselect;                                       // mm_interconnect_0:GPIO3_s1_chipselect -> GPIO3:chipselect
	wire  [31:0] mm_interconnect_0_gpio3_s1_readdata;                                         // GPIO3:readdata -> mm_interconnect_0:GPIO3_s1_readdata
	wire   [1:0] mm_interconnect_0_gpio3_s1_address;                                          // mm_interconnect_0:GPIO3_s1_address -> GPIO3:address
	wire         mm_interconnect_0_gpio3_s1_write;                                            // mm_interconnect_0:GPIO3_s1_write -> GPIO3:write_n
	wire  [31:0] mm_interconnect_0_gpio3_s1_writedata;                                        // mm_interconnect_0:GPIO3_s1_writedata -> GPIO3:writedata
	wire         mm_interconnect_0_sdram_s1_chipselect;                                       // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                                         // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                                      // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire  [24:0] mm_interconnect_0_sdram_s1_address;                                          // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire         mm_interconnect_0_sdram_s1_read;                                             // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                                       // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                                    // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire         mm_interconnect_0_sdram_s1_write;                                            // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                                        // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire  [31:0] mm_interconnect_0_pb_sw_1_s1_readdata;                                       // PB_SW_1:readdata -> mm_interconnect_0:PB_SW_1_s1_readdata
	wire   [1:0] mm_interconnect_0_pb_sw_1_s1_address;                                        // mm_interconnect_0:PB_SW_1_s1_address -> PB_SW_1:address
	wire  [31:0] mm_interconnect_0_pb_sw_2_s1_readdata;                                       // PB_SW_2:readdata -> mm_interconnect_0:PB_SW_2_s1_readdata
	wire   [1:0] mm_interconnect_0_pb_sw_2_s1_address;                                        // mm_interconnect_0:PB_SW_2_s1_address -> PB_SW_2:address
	wire         mm_interconnect_0_seven_seg_0_s1_chipselect;                                 // mm_interconnect_0:SEVEN_SEG_0_s1_chipselect -> SEVEN_SEG_0:chipselect
	wire  [31:0] mm_interconnect_0_seven_seg_0_s1_readdata;                                   // SEVEN_SEG_0:readdata -> mm_interconnect_0:SEVEN_SEG_0_s1_readdata
	wire   [1:0] mm_interconnect_0_seven_seg_0_s1_address;                                    // mm_interconnect_0:SEVEN_SEG_0_s1_address -> SEVEN_SEG_0:address
	wire         mm_interconnect_0_seven_seg_0_s1_write;                                      // mm_interconnect_0:SEVEN_SEG_0_s1_write -> SEVEN_SEG_0:write_n
	wire  [31:0] mm_interconnect_0_seven_seg_0_s1_writedata;                                  // mm_interconnect_0:SEVEN_SEG_0_s1_writedata -> SEVEN_SEG_0:writedata
	wire         mm_interconnect_0_seven_seg_1_s1_chipselect;                                 // mm_interconnect_0:SEVEN_SEG_1_s1_chipselect -> SEVEN_SEG_1:chipselect
	wire  [31:0] mm_interconnect_0_seven_seg_1_s1_readdata;                                   // SEVEN_SEG_1:readdata -> mm_interconnect_0:SEVEN_SEG_1_s1_readdata
	wire   [1:0] mm_interconnect_0_seven_seg_1_s1_address;                                    // mm_interconnect_0:SEVEN_SEG_1_s1_address -> SEVEN_SEG_1:address
	wire         mm_interconnect_0_seven_seg_1_s1_write;                                      // mm_interconnect_0:SEVEN_SEG_1_s1_write -> SEVEN_SEG_1:write_n
	wire  [31:0] mm_interconnect_0_seven_seg_1_s1_writedata;                                  // mm_interconnect_0:SEVEN_SEG_1_s1_writedata -> SEVEN_SEG_1:writedata
	wire         mm_interconnect_0_seven_seg_2_s1_chipselect;                                 // mm_interconnect_0:SEVEN_SEG_2_s1_chipselect -> SEVEN_SEG_2:chipselect
	wire  [31:0] mm_interconnect_0_seven_seg_2_s1_readdata;                                   // SEVEN_SEG_2:readdata -> mm_interconnect_0:SEVEN_SEG_2_s1_readdata
	wire   [1:0] mm_interconnect_0_seven_seg_2_s1_address;                                    // mm_interconnect_0:SEVEN_SEG_2_s1_address -> SEVEN_SEG_2:address
	wire         mm_interconnect_0_seven_seg_2_s1_write;                                      // mm_interconnect_0:SEVEN_SEG_2_s1_write -> SEVEN_SEG_2:write_n
	wire  [31:0] mm_interconnect_0_seven_seg_2_s1_writedata;                                  // mm_interconnect_0:SEVEN_SEG_2_s1_writedata -> SEVEN_SEG_2:writedata
	wire         mm_interconnect_0_seven_seg_3_s1_chipselect;                                 // mm_interconnect_0:SEVEN_SEG_3_s1_chipselect -> SEVEN_SEG_3:chipselect
	wire  [31:0] mm_interconnect_0_seven_seg_3_s1_readdata;                                   // SEVEN_SEG_3:readdata -> mm_interconnect_0:SEVEN_SEG_3_s1_readdata
	wire   [1:0] mm_interconnect_0_seven_seg_3_s1_address;                                    // mm_interconnect_0:SEVEN_SEG_3_s1_address -> SEVEN_SEG_3:address
	wire         mm_interconnect_0_seven_seg_3_s1_write;                                      // mm_interconnect_0:SEVEN_SEG_3_s1_write -> SEVEN_SEG_3:write_n
	wire  [31:0] mm_interconnect_0_seven_seg_3_s1_writedata;                                  // mm_interconnect_0:SEVEN_SEG_3_s1_writedata -> SEVEN_SEG_3:writedata
	wire         mm_interconnect_0_seven_seg_4_s1_chipselect;                                 // mm_interconnect_0:SEVEN_SEG_4_s1_chipselect -> SEVEN_SEG_4:chipselect
	wire  [31:0] mm_interconnect_0_seven_seg_4_s1_readdata;                                   // SEVEN_SEG_4:readdata -> mm_interconnect_0:SEVEN_SEG_4_s1_readdata
	wire   [1:0] mm_interconnect_0_seven_seg_4_s1_address;                                    // mm_interconnect_0:SEVEN_SEG_4_s1_address -> SEVEN_SEG_4:address
	wire         mm_interconnect_0_seven_seg_4_s1_write;                                      // mm_interconnect_0:SEVEN_SEG_4_s1_write -> SEVEN_SEG_4:write_n
	wire  [31:0] mm_interconnect_0_seven_seg_4_s1_writedata;                                  // mm_interconnect_0:SEVEN_SEG_4_s1_writedata -> SEVEN_SEG_4:writedata
	wire         mm_interconnect_0_seven_seg_5_s1_chipselect;                                 // mm_interconnect_0:SEVEN_SEG_5_s1_chipselect -> SEVEN_SEG_5:chipselect
	wire  [31:0] mm_interconnect_0_seven_seg_5_s1_readdata;                                   // SEVEN_SEG_5:readdata -> mm_interconnect_0:SEVEN_SEG_5_s1_readdata
	wire   [1:0] mm_interconnect_0_seven_seg_5_s1_address;                                    // mm_interconnect_0:SEVEN_SEG_5_s1_address -> SEVEN_SEG_5:address
	wire         mm_interconnect_0_seven_seg_5_s1_write;                                      // mm_interconnect_0:SEVEN_SEG_5_s1_write -> SEVEN_SEG_5:write_n
	wire  [31:0] mm_interconnect_0_seven_seg_5_s1_writedata;                                  // mm_interconnect_0:SEVEN_SEG_5_s1_writedata -> SEVEN_SEG_5:writedata
	wire         mm_interconnect_0_pixel_data_s1_chipselect;                                  // mm_interconnect_0:PIXEL_DATA_s1_chipselect -> PIXEL_DATA:chipselect
	wire  [31:0] mm_interconnect_0_pixel_data_s1_readdata;                                    // PIXEL_DATA:readdata -> mm_interconnect_0:PIXEL_DATA_s1_readdata
	wire   [1:0] mm_interconnect_0_pixel_data_s1_address;                                     // mm_interconnect_0:PIXEL_DATA_s1_address -> PIXEL_DATA:address
	wire         mm_interconnect_0_pixel_data_s1_write;                                       // mm_interconnect_0:PIXEL_DATA_s1_write -> PIXEL_DATA:write_n
	wire  [31:0] mm_interconnect_0_pixel_data_s1_writedata;                                   // mm_interconnect_0:PIXEL_DATA_s1_writedata -> PIXEL_DATA:writedata
	wire  [31:0] mm_interconnect_0_camera_ready_s1_readdata;                                  // CAMERA_READY:readdata -> mm_interconnect_0:CAMERA_READY_s1_readdata
	wire   [1:0] mm_interconnect_0_camera_ready_s1_address;                                   // mm_interconnect_0:CAMERA_READY_s1_address -> CAMERA_READY:address
	wire         mm_interconnect_0_img_addr_dram_s1_chipselect;                               // mm_interconnect_0:IMG_ADDR_DRAM_s1_chipselect -> IMG_ADDR_DRAM:chipselect
	wire  [31:0] mm_interconnect_0_img_addr_dram_s1_readdata;                                 // IMG_ADDR_DRAM:readdata -> mm_interconnect_0:IMG_ADDR_DRAM_s1_readdata
	wire   [1:0] mm_interconnect_0_img_addr_dram_s1_address;                                  // mm_interconnect_0:IMG_ADDR_DRAM_s1_address -> IMG_ADDR_DRAM:address
	wire         mm_interconnect_0_img_addr_dram_s1_write;                                    // mm_interconnect_0:IMG_ADDR_DRAM_s1_write -> IMG_ADDR_DRAM:write_n
	wire  [31:0] mm_interconnect_0_img_addr_dram_s1_writedata;                                // mm_interconnect_0:IMG_ADDR_DRAM_s1_writedata -> IMG_ADDR_DRAM:writedata
	wire         mm_interconnect_0_write_enable_s1_chipselect;                                // mm_interconnect_0:WRITE_ENABLE_s1_chipselect -> WRITE_ENABLE:chipselect
	wire  [31:0] mm_interconnect_0_write_enable_s1_readdata;                                  // WRITE_ENABLE:readdata -> mm_interconnect_0:WRITE_ENABLE_s1_readdata
	wire   [1:0] mm_interconnect_0_write_enable_s1_address;                                   // mm_interconnect_0:WRITE_ENABLE_s1_address -> WRITE_ENABLE:address
	wire         mm_interconnect_0_write_enable_s1_write;                                     // mm_interconnect_0:WRITE_ENABLE_s1_write -> WRITE_ENABLE:write_n
	wire  [31:0] mm_interconnect_0_write_enable_s1_writedata;                                 // mm_interconnect_0:WRITE_ENABLE_s1_writedata -> WRITE_ENABLE:writedata
	wire         mm_interconnect_0_spi_spi_control_port_chipselect;                           // mm_interconnect_0:SPI_spi_control_port_chipselect -> SPI:spi_select
	wire  [15:0] mm_interconnect_0_spi_spi_control_port_readdata;                             // SPI:data_to_cpu -> mm_interconnect_0:SPI_spi_control_port_readdata
	wire   [2:0] mm_interconnect_0_spi_spi_control_port_address;                              // mm_interconnect_0:SPI_spi_control_port_address -> SPI:mem_addr
	wire         mm_interconnect_0_spi_spi_control_port_read;                                 // mm_interconnect_0:SPI_spi_control_port_read -> SPI:read_n
	wire         mm_interconnect_0_spi_spi_control_port_write;                                // mm_interconnect_0:SPI_spi_control_port_write -> SPI:write_n
	wire  [15:0] mm_interconnect_0_spi_spi_control_port_writedata;                            // mm_interconnect_0:SPI_spi_control_port_writedata -> SPI:data_from_cpu
	wire         irq_mapper_receiver0_irq;                                                    // ACCEL_SPI:irq -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                                                    // jtag_uart_0:av_irq -> irq_mapper:receiver1_irq
	wire         irq_mapper_receiver2_irq;                                                    // SPI:irq -> irq_mapper:receiver2_irq
	wire  [31:0] nios2_gen2_0_irq_irq;                                                        // irq_mapper:sender_irq -> nios2_gen2_0:irq
	wire         rst_controller_reset_out_reset;                                              // rst_controller:reset_out -> [ACCEL_SPI:reset, CAMERA_READY:reset_n, GPIO3:reset_n, IMG_ADDR_DRAM:reset_n, LEDR:reset_n, PB_SW_1:reset_n, PB_SW_2:reset_n, PIXEL_DATA:reset_n, SDRAM:reset_n, SEVEN_SEG_0:reset_n, SEVEN_SEG_1:reset_n, SEVEN_SEG_2:reset_n, SEVEN_SEG_3:reset_n, SEVEN_SEG_4:reset_n, SEVEN_SEG_5:reset_n, SPI:reset_n, WRITE_ENABLE:reset_n, irq_mapper:reset, jtag_uart_0:rst_n, mm_interconnect_0:nios2_gen2_0_reset_reset_bridge_in_reset_reset, nios2_gen2_0:reset_n, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                                          // rst_controller:reset_req -> [nios2_gen2_0:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                                          // rst_controller_001:reset_out -> [SRAM:reset, mm_interconnect_0:SRAM_reset1_reset_bridge_in_reset_reset]
	wire         rst_controller_001_reset_out_reset_req;                                      // rst_controller_001:reset_req -> SRAM:reset_req

	NIOS2_WEEK2_ACCEL_SPI accel_spi (
		.clk           (clk_clk),                                                                     //                                 clk.clk
		.reset         (rst_controller_reset_out_reset),                                              //                               reset.reset
		.address       (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_address),     // avalon_accelerometer_spi_mode_slave.address
		.byteenable    (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_byteenable),  //                                    .byteenable
		.read          (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_read),        //                                    .read
		.write         (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_write),       //                                    .write
		.writedata     (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_writedata),   //                                    .writedata
		.readdata      (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_readdata),    //                                    .readdata
		.waitrequest   (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_waitrequest), //                                    .waitrequest
		.irq           (irq_mapper_receiver0_irq),                                                    //                           interrupt.irq
		.I2C_SDAT      (accel_I2C_SDAT),                                                              //                  external_interface.export
		.I2C_SCLK      (accel_I2C_SCLK),                                                              //                                    .export
		.G_SENSOR_CS_N (accel_G_SENSOR_CS_N),                                                         //                                    .export
		.G_SENSOR_INT  (accel_G_SENSOR_INT)                                                           //                                    .export
	);

	NIOS2_WEEK2_CAMERA_READY camera_ready (
		.clk      (clk_clk),                                    //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),            //               reset.reset_n
		.address  (mm_interconnect_0_camera_ready_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_camera_ready_s1_readdata), //                    .readdata
		.in_port  (camera_ready_export)                         // external_connection.export
	);

	NIOS2_WEEK2_GPIO3 gpio3 (
		.clk        (clk_clk),                               //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address    (mm_interconnect_0_gpio3_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_gpio3_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_gpio3_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_gpio3_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_gpio3_s1_readdata),   //                    .readdata
		.out_port   (gpio_export)                            // external_connection.export
	);

	NIOS2_WEEK2_IMG_ADDR_DRAM img_addr_dram (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address    (mm_interconnect_0_img_addr_dram_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_img_addr_dram_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_img_addr_dram_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_img_addr_dram_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_img_addr_dram_s1_readdata),   //                    .readdata
		.out_port   (img_addr_export)                                // external_connection.export
	);

	NIOS2_WEEK2_LEDR ledr (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_ledr_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_ledr_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_ledr_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_ledr_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_ledr_s1_readdata),   //                    .readdata
		.out_port   (led_export)                            // external_connection.export
	);

	NIOS2_WEEK2_CAMERA_READY pb_sw_1 (
		.clk      (clk_clk),                               //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_pb_sw_1_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pb_sw_1_s1_readdata), //                    .readdata
		.in_port  (key1_export)                            // external_connection.export
	);

	NIOS2_WEEK2_CAMERA_READY pb_sw_2 (
		.clk      (clk_clk),                               //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_pb_sw_2_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pb_sw_2_s1_readdata), //                    .readdata
		.in_port  (key2_export)                            // external_connection.export
	);

	NIOS2_WEEK2_PIXEL_DATA pixel_data (
		.clk        (clk_clk),                                    //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),            //               reset.reset_n
		.address    (mm_interconnect_0_pixel_data_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pixel_data_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pixel_data_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pixel_data_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pixel_data_s1_readdata),   //                    .readdata
		.out_port   (pixel_export)                                // external_connection.export
	);

	NIOS2_WEEK2_SDRAM sdram (
		.clk            (clk_clk),                                  //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (dram_addr),                                //  wire.export
		.zs_ba          (dram_ba),                                  //      .export
		.zs_cas_n       (dram_cas_n),                               //      .export
		.zs_cke         (dram_cke),                                 //      .export
		.zs_cs_n        (dram_cs_n),                                //      .export
		.zs_dq          (dram_dq),                                  //      .export
		.zs_dqm         (dram_dqm),                                 //      .export
		.zs_ras_n       (dram_ras_n),                               //      .export
		.zs_we_n        (dram_we_n)                                 //      .export
	);

	NIOS2_WEEK2_SEVEN_SEG_0 seven_seg_0 (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_seven_seg_0_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seven_seg_0_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seven_seg_0_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seven_seg_0_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seven_seg_0_s1_readdata),   //                    .readdata
		.out_port   (seven_seg_0_export)                           // external_connection.export
	);

	NIOS2_WEEK2_SEVEN_SEG_0 seven_seg_1 (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_seven_seg_1_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seven_seg_1_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seven_seg_1_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seven_seg_1_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seven_seg_1_s1_readdata),   //                    .readdata
		.out_port   (seven_seg_1_export)                           // external_connection.export
	);

	NIOS2_WEEK2_SEVEN_SEG_0 seven_seg_2 (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_seven_seg_2_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seven_seg_2_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seven_seg_2_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seven_seg_2_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seven_seg_2_s1_readdata),   //                    .readdata
		.out_port   (seven_seg_2_export)                           // external_connection.export
	);

	NIOS2_WEEK2_SEVEN_SEG_0 seven_seg_3 (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_seven_seg_3_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seven_seg_3_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seven_seg_3_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seven_seg_3_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seven_seg_3_s1_readdata),   //                    .readdata
		.out_port   (seven_seg_3_export)                           // external_connection.export
	);

	NIOS2_WEEK2_SEVEN_SEG_0 seven_seg_4 (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_seven_seg_4_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seven_seg_4_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seven_seg_4_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seven_seg_4_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seven_seg_4_s1_readdata),   //                    .readdata
		.out_port   (seven_seg_4_export)                           // external_connection.export
	);

	NIOS2_WEEK2_SEVEN_SEG_0 seven_seg_5 (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_seven_seg_5_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_seven_seg_5_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_seven_seg_5_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_seven_seg_5_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_seven_seg_5_s1_readdata),   //                    .readdata
		.out_port   (seven_seg_5_export)                           // external_connection.export
	);

	NIOS2_WEEK2_SPI spi (
		.clk           (clk_clk),                                           //              clk.clk
		.reset_n       (~rst_controller_reset_out_reset),                   //            reset.reset_n
		.data_from_cpu (mm_interconnect_0_spi_spi_control_port_writedata),  // spi_control_port.writedata
		.data_to_cpu   (mm_interconnect_0_spi_spi_control_port_readdata),   //                 .readdata
		.mem_addr      (mm_interconnect_0_spi_spi_control_port_address),    //                 .address
		.read_n        (~mm_interconnect_0_spi_spi_control_port_read),      //                 .read_n
		.spi_select    (mm_interconnect_0_spi_spi_control_port_chipselect), //                 .chipselect
		.write_n       (~mm_interconnect_0_spi_spi_control_port_write),     //                 .write_n
		.irq           (irq_mapper_receiver2_irq),                          //              irq.irq
		.MISO          (spi_peripheral_MISO),                               //         external.export
		.MOSI          (spi_peripheral_MOSI),                               //                 .export
		.SCLK          (spi_peripheral_SCLK),                               //                 .export
		.SS_n          (spi_peripheral_SS_n)                                //                 .export
	);

	NIOS2_WEEK2_SRAM sram (
		.clk        (clk_clk),                                //   clk1.clk
		.address    (mm_interconnect_0_sram_s1_address),      //     s1.address
		.clken      (mm_interconnect_0_sram_s1_clken),        //       .clken
		.chipselect (mm_interconnect_0_sram_s1_chipselect),   //       .chipselect
		.write      (mm_interconnect_0_sram_s1_write),        //       .write
		.readdata   (mm_interconnect_0_sram_s1_readdata),     //       .readdata
		.writedata  (mm_interconnect_0_sram_s1_writedata),    //       .writedata
		.byteenable (mm_interconnect_0_sram_s1_byteenable),   //       .byteenable
		.reset      (rst_controller_001_reset_out_reset),     // reset1.reset
		.reset_req  (rst_controller_001_reset_out_reset_req), //       .reset_req
		.freeze     (1'b0)                                    // (terminated)
	);

	NIOS2_WEEK2_GPIO3 write_enable (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_write_enable_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_write_enable_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_write_enable_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_write_enable_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_write_enable_s1_readdata),   //                    .readdata
		.out_port   (wren_export)                                   // external_connection.export
	);

	NIOS2_WEEK2_jtag_uart_0 jtag_uart_0 (
		.clk            (clk_clk),                                                     //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                             //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver1_irq)                                     //               irq.irq
	);

	NIOS2_WEEK2_nios2_gen2_0 nios2_gen2_0 (
		.clk                                 (clk_clk),                                                    //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                            //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                         //                          .reset_req
		.d_address                           (nios2_gen2_0_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios2_gen2_0_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios2_gen2_0_data_master_read),                              //                          .read
		.d_readdata                          (nios2_gen2_0_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios2_gen2_0_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios2_gen2_0_data_master_write),                             //                          .write
		.d_writedata                         (nios2_gen2_0_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (nios2_gen2_0_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios2_gen2_0_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios2_gen2_0_instruction_master_read),                       //                          .read
		.i_readdata                          (nios2_gen2_0_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios2_gen2_0_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (nios2_gen2_0_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios2_gen2_0_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                            // custom_instruction_master.readra
	);

	NIOS2_WEEK2_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                             (clk_clk),                                                                     //                                     clk_0_clk.clk
		.nios2_gen2_0_reset_reset_bridge_in_reset_reset            (rst_controller_reset_out_reset),                                              //      nios2_gen2_0_reset_reset_bridge_in_reset.reset
		.SRAM_reset1_reset_bridge_in_reset_reset                   (rst_controller_001_reset_out_reset),                                          //             SRAM_reset1_reset_bridge_in_reset.reset
		.nios2_gen2_0_data_master_address                          (nios2_gen2_0_data_master_address),                                            //                      nios2_gen2_0_data_master.address
		.nios2_gen2_0_data_master_waitrequest                      (nios2_gen2_0_data_master_waitrequest),                                        //                                              .waitrequest
		.nios2_gen2_0_data_master_byteenable                       (nios2_gen2_0_data_master_byteenable),                                         //                                              .byteenable
		.nios2_gen2_0_data_master_read                             (nios2_gen2_0_data_master_read),                                               //                                              .read
		.nios2_gen2_0_data_master_readdata                         (nios2_gen2_0_data_master_readdata),                                           //                                              .readdata
		.nios2_gen2_0_data_master_write                            (nios2_gen2_0_data_master_write),                                              //                                              .write
		.nios2_gen2_0_data_master_writedata                        (nios2_gen2_0_data_master_writedata),                                          //                                              .writedata
		.nios2_gen2_0_data_master_debugaccess                      (nios2_gen2_0_data_master_debugaccess),                                        //                                              .debugaccess
		.nios2_gen2_0_instruction_master_address                   (nios2_gen2_0_instruction_master_address),                                     //               nios2_gen2_0_instruction_master.address
		.nios2_gen2_0_instruction_master_waitrequest               (nios2_gen2_0_instruction_master_waitrequest),                                 //                                              .waitrequest
		.nios2_gen2_0_instruction_master_read                      (nios2_gen2_0_instruction_master_read),                                        //                                              .read
		.nios2_gen2_0_instruction_master_readdata                  (nios2_gen2_0_instruction_master_readdata),                                    //                                              .readdata
		.ACCEL_SPI_avalon_accelerometer_spi_mode_slave_address     (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_address),     // ACCEL_SPI_avalon_accelerometer_spi_mode_slave.address
		.ACCEL_SPI_avalon_accelerometer_spi_mode_slave_write       (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_write),       //                                              .write
		.ACCEL_SPI_avalon_accelerometer_spi_mode_slave_read        (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_read),        //                                              .read
		.ACCEL_SPI_avalon_accelerometer_spi_mode_slave_readdata    (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_readdata),    //                                              .readdata
		.ACCEL_SPI_avalon_accelerometer_spi_mode_slave_writedata   (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_writedata),   //                                              .writedata
		.ACCEL_SPI_avalon_accelerometer_spi_mode_slave_byteenable  (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_byteenable),  //                                              .byteenable
		.ACCEL_SPI_avalon_accelerometer_spi_mode_slave_waitrequest (mm_interconnect_0_accel_spi_avalon_accelerometer_spi_mode_slave_waitrequest), //                                              .waitrequest
		.CAMERA_READY_s1_address                                   (mm_interconnect_0_camera_ready_s1_address),                                   //                               CAMERA_READY_s1.address
		.CAMERA_READY_s1_readdata                                  (mm_interconnect_0_camera_ready_s1_readdata),                                  //                                              .readdata
		.GPIO3_s1_address                                          (mm_interconnect_0_gpio3_s1_address),                                          //                                      GPIO3_s1.address
		.GPIO3_s1_write                                            (mm_interconnect_0_gpio3_s1_write),                                            //                                              .write
		.GPIO3_s1_readdata                                         (mm_interconnect_0_gpio3_s1_readdata),                                         //                                              .readdata
		.GPIO3_s1_writedata                                        (mm_interconnect_0_gpio3_s1_writedata),                                        //                                              .writedata
		.GPIO3_s1_chipselect                                       (mm_interconnect_0_gpio3_s1_chipselect),                                       //                                              .chipselect
		.IMG_ADDR_DRAM_s1_address                                  (mm_interconnect_0_img_addr_dram_s1_address),                                  //                              IMG_ADDR_DRAM_s1.address
		.IMG_ADDR_DRAM_s1_write                                    (mm_interconnect_0_img_addr_dram_s1_write),                                    //                                              .write
		.IMG_ADDR_DRAM_s1_readdata                                 (mm_interconnect_0_img_addr_dram_s1_readdata),                                 //                                              .readdata
		.IMG_ADDR_DRAM_s1_writedata                                (mm_interconnect_0_img_addr_dram_s1_writedata),                                //                                              .writedata
		.IMG_ADDR_DRAM_s1_chipselect                               (mm_interconnect_0_img_addr_dram_s1_chipselect),                               //                                              .chipselect
		.jtag_uart_0_avalon_jtag_slave_address                     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),                     //                 jtag_uart_0_avalon_jtag_slave.address
		.jtag_uart_0_avalon_jtag_slave_write                       (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),                       //                                              .write
		.jtag_uart_0_avalon_jtag_slave_read                        (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),                        //                                              .read
		.jtag_uart_0_avalon_jtag_slave_readdata                    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),                    //                                              .readdata
		.jtag_uart_0_avalon_jtag_slave_writedata                   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),                   //                                              .writedata
		.jtag_uart_0_avalon_jtag_slave_waitrequest                 (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest),                 //                                              .waitrequest
		.jtag_uart_0_avalon_jtag_slave_chipselect                  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),                  //                                              .chipselect
		.LEDR_s1_address                                           (mm_interconnect_0_ledr_s1_address),                                           //                                       LEDR_s1.address
		.LEDR_s1_write                                             (mm_interconnect_0_ledr_s1_write),                                             //                                              .write
		.LEDR_s1_readdata                                          (mm_interconnect_0_ledr_s1_readdata),                                          //                                              .readdata
		.LEDR_s1_writedata                                         (mm_interconnect_0_ledr_s1_writedata),                                         //                                              .writedata
		.LEDR_s1_chipselect                                        (mm_interconnect_0_ledr_s1_chipselect),                                        //                                              .chipselect
		.nios2_gen2_0_debug_mem_slave_address                      (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address),                      //                  nios2_gen2_0_debug_mem_slave.address
		.nios2_gen2_0_debug_mem_slave_write                        (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write),                        //                                              .write
		.nios2_gen2_0_debug_mem_slave_read                         (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read),                         //                                              .read
		.nios2_gen2_0_debug_mem_slave_readdata                     (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata),                     //                                              .readdata
		.nios2_gen2_0_debug_mem_slave_writedata                    (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata),                    //                                              .writedata
		.nios2_gen2_0_debug_mem_slave_byteenable                   (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable),                   //                                              .byteenable
		.nios2_gen2_0_debug_mem_slave_waitrequest                  (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest),                  //                                              .waitrequest
		.nios2_gen2_0_debug_mem_slave_debugaccess                  (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess),                  //                                              .debugaccess
		.PB_SW_1_s1_address                                        (mm_interconnect_0_pb_sw_1_s1_address),                                        //                                    PB_SW_1_s1.address
		.PB_SW_1_s1_readdata                                       (mm_interconnect_0_pb_sw_1_s1_readdata),                                       //                                              .readdata
		.PB_SW_2_s1_address                                        (mm_interconnect_0_pb_sw_2_s1_address),                                        //                                    PB_SW_2_s1.address
		.PB_SW_2_s1_readdata                                       (mm_interconnect_0_pb_sw_2_s1_readdata),                                       //                                              .readdata
		.PIXEL_DATA_s1_address                                     (mm_interconnect_0_pixel_data_s1_address),                                     //                                 PIXEL_DATA_s1.address
		.PIXEL_DATA_s1_write                                       (mm_interconnect_0_pixel_data_s1_write),                                       //                                              .write
		.PIXEL_DATA_s1_readdata                                    (mm_interconnect_0_pixel_data_s1_readdata),                                    //                                              .readdata
		.PIXEL_DATA_s1_writedata                                   (mm_interconnect_0_pixel_data_s1_writedata),                                   //                                              .writedata
		.PIXEL_DATA_s1_chipselect                                  (mm_interconnect_0_pixel_data_s1_chipselect),                                  //                                              .chipselect
		.SDRAM_s1_address                                          (mm_interconnect_0_sdram_s1_address),                                          //                                      SDRAM_s1.address
		.SDRAM_s1_write                                            (mm_interconnect_0_sdram_s1_write),                                            //                                              .write
		.SDRAM_s1_read                                             (mm_interconnect_0_sdram_s1_read),                                             //                                              .read
		.SDRAM_s1_readdata                                         (mm_interconnect_0_sdram_s1_readdata),                                         //                                              .readdata
		.SDRAM_s1_writedata                                        (mm_interconnect_0_sdram_s1_writedata),                                        //                                              .writedata
		.SDRAM_s1_byteenable                                       (mm_interconnect_0_sdram_s1_byteenable),                                       //                                              .byteenable
		.SDRAM_s1_readdatavalid                                    (mm_interconnect_0_sdram_s1_readdatavalid),                                    //                                              .readdatavalid
		.SDRAM_s1_waitrequest                                      (mm_interconnect_0_sdram_s1_waitrequest),                                      //                                              .waitrequest
		.SDRAM_s1_chipselect                                       (mm_interconnect_0_sdram_s1_chipselect),                                       //                                              .chipselect
		.SEVEN_SEG_0_s1_address                                    (mm_interconnect_0_seven_seg_0_s1_address),                                    //                                SEVEN_SEG_0_s1.address
		.SEVEN_SEG_0_s1_write                                      (mm_interconnect_0_seven_seg_0_s1_write),                                      //                                              .write
		.SEVEN_SEG_0_s1_readdata                                   (mm_interconnect_0_seven_seg_0_s1_readdata),                                   //                                              .readdata
		.SEVEN_SEG_0_s1_writedata                                  (mm_interconnect_0_seven_seg_0_s1_writedata),                                  //                                              .writedata
		.SEVEN_SEG_0_s1_chipselect                                 (mm_interconnect_0_seven_seg_0_s1_chipselect),                                 //                                              .chipselect
		.SEVEN_SEG_1_s1_address                                    (mm_interconnect_0_seven_seg_1_s1_address),                                    //                                SEVEN_SEG_1_s1.address
		.SEVEN_SEG_1_s1_write                                      (mm_interconnect_0_seven_seg_1_s1_write),                                      //                                              .write
		.SEVEN_SEG_1_s1_readdata                                   (mm_interconnect_0_seven_seg_1_s1_readdata),                                   //                                              .readdata
		.SEVEN_SEG_1_s1_writedata                                  (mm_interconnect_0_seven_seg_1_s1_writedata),                                  //                                              .writedata
		.SEVEN_SEG_1_s1_chipselect                                 (mm_interconnect_0_seven_seg_1_s1_chipselect),                                 //                                              .chipselect
		.SEVEN_SEG_2_s1_address                                    (mm_interconnect_0_seven_seg_2_s1_address),                                    //                                SEVEN_SEG_2_s1.address
		.SEVEN_SEG_2_s1_write                                      (mm_interconnect_0_seven_seg_2_s1_write),                                      //                                              .write
		.SEVEN_SEG_2_s1_readdata                                   (mm_interconnect_0_seven_seg_2_s1_readdata),                                   //                                              .readdata
		.SEVEN_SEG_2_s1_writedata                                  (mm_interconnect_0_seven_seg_2_s1_writedata),                                  //                                              .writedata
		.SEVEN_SEG_2_s1_chipselect                                 (mm_interconnect_0_seven_seg_2_s1_chipselect),                                 //                                              .chipselect
		.SEVEN_SEG_3_s1_address                                    (mm_interconnect_0_seven_seg_3_s1_address),                                    //                                SEVEN_SEG_3_s1.address
		.SEVEN_SEG_3_s1_write                                      (mm_interconnect_0_seven_seg_3_s1_write),                                      //                                              .write
		.SEVEN_SEG_3_s1_readdata                                   (mm_interconnect_0_seven_seg_3_s1_readdata),                                   //                                              .readdata
		.SEVEN_SEG_3_s1_writedata                                  (mm_interconnect_0_seven_seg_3_s1_writedata),                                  //                                              .writedata
		.SEVEN_SEG_3_s1_chipselect                                 (mm_interconnect_0_seven_seg_3_s1_chipselect),                                 //                                              .chipselect
		.SEVEN_SEG_4_s1_address                                    (mm_interconnect_0_seven_seg_4_s1_address),                                    //                                SEVEN_SEG_4_s1.address
		.SEVEN_SEG_4_s1_write                                      (mm_interconnect_0_seven_seg_4_s1_write),                                      //                                              .write
		.SEVEN_SEG_4_s1_readdata                                   (mm_interconnect_0_seven_seg_4_s1_readdata),                                   //                                              .readdata
		.SEVEN_SEG_4_s1_writedata                                  (mm_interconnect_0_seven_seg_4_s1_writedata),                                  //                                              .writedata
		.SEVEN_SEG_4_s1_chipselect                                 (mm_interconnect_0_seven_seg_4_s1_chipselect),                                 //                                              .chipselect
		.SEVEN_SEG_5_s1_address                                    (mm_interconnect_0_seven_seg_5_s1_address),                                    //                                SEVEN_SEG_5_s1.address
		.SEVEN_SEG_5_s1_write                                      (mm_interconnect_0_seven_seg_5_s1_write),                                      //                                              .write
		.SEVEN_SEG_5_s1_readdata                                   (mm_interconnect_0_seven_seg_5_s1_readdata),                                   //                                              .readdata
		.SEVEN_SEG_5_s1_writedata                                  (mm_interconnect_0_seven_seg_5_s1_writedata),                                  //                                              .writedata
		.SEVEN_SEG_5_s1_chipselect                                 (mm_interconnect_0_seven_seg_5_s1_chipselect),                                 //                                              .chipselect
		.SPI_spi_control_port_address                              (mm_interconnect_0_spi_spi_control_port_address),                              //                          SPI_spi_control_port.address
		.SPI_spi_control_port_write                                (mm_interconnect_0_spi_spi_control_port_write),                                //                                              .write
		.SPI_spi_control_port_read                                 (mm_interconnect_0_spi_spi_control_port_read),                                 //                                              .read
		.SPI_spi_control_port_readdata                             (mm_interconnect_0_spi_spi_control_port_readdata),                             //                                              .readdata
		.SPI_spi_control_port_writedata                            (mm_interconnect_0_spi_spi_control_port_writedata),                            //                                              .writedata
		.SPI_spi_control_port_chipselect                           (mm_interconnect_0_spi_spi_control_port_chipselect),                           //                                              .chipselect
		.SRAM_s1_address                                           (mm_interconnect_0_sram_s1_address),                                           //                                       SRAM_s1.address
		.SRAM_s1_write                                             (mm_interconnect_0_sram_s1_write),                                             //                                              .write
		.SRAM_s1_readdata                                          (mm_interconnect_0_sram_s1_readdata),                                          //                                              .readdata
		.SRAM_s1_writedata                                         (mm_interconnect_0_sram_s1_writedata),                                         //                                              .writedata
		.SRAM_s1_byteenable                                        (mm_interconnect_0_sram_s1_byteenable),                                        //                                              .byteenable
		.SRAM_s1_chipselect                                        (mm_interconnect_0_sram_s1_chipselect),                                        //                                              .chipselect
		.SRAM_s1_clken                                             (mm_interconnect_0_sram_s1_clken),                                             //                                              .clken
		.WRITE_ENABLE_s1_address                                   (mm_interconnect_0_write_enable_s1_address),                                   //                               WRITE_ENABLE_s1.address
		.WRITE_ENABLE_s1_write                                     (mm_interconnect_0_write_enable_s1_write),                                     //                                              .write
		.WRITE_ENABLE_s1_readdata                                  (mm_interconnect_0_write_enable_s1_readdata),                                  //                                              .readdata
		.WRITE_ENABLE_s1_writedata                                 (mm_interconnect_0_write_enable_s1_writedata),                                 //                                              .writedata
		.WRITE_ENABLE_s1_chipselect                                (mm_interconnect_0_write_enable_s1_chipselect)                                 //                                              .chipselect
	);

	NIOS2_WEEK2_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.receiver2_irq (irq_mapper_receiver2_irq),       // receiver2.irq
		.sender_irq    (nios2_gen2_0_irq_irq)            //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (nios2_gen2_0_debug_reset_request_reset), // reset_in0.reset
		.reset_in1      (nios2_gen2_0_debug_reset_request_reset), // reset_in1.reset
		.clk            (clk_clk),                                //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),         // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req),     //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (nios2_gen2_0_debug_reset_request_reset), // reset_in0.reset
		.clk            (clk_clk),                                //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_in1      (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

endmodule
