/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'NIOS2_WEEK2'
 * SOPC Builder design path: ../../NIOS2_WEEK2.sopcinfo
 *
 * Generated: Mon Mar 30 14:36:58 SGT 2026
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * ACCEL_SPI configuration
 *
 */

#define ACCEL_SPI_BASE 0x4009110
#define ACCEL_SPI_IRQ 0
#define ACCEL_SPI_IRQ_INTERRUPT_CONTROLLER_ID 0
#define ACCEL_SPI_NAME "/dev/ACCEL_SPI"
#define ACCEL_SPI_SPAN 2
#define ACCEL_SPI_TYPE "altera_up_avalon_accelerometer_spi"
#define ALT_MODULE_CLASS_ACCEL_SPI altera_up_avalon_accelerometer_spi


/*
 * CAMERA_READY configuration
 *
 */

#define ALT_MODULE_CLASS_CAMERA_READY altera_avalon_pio
#define CAMERA_READY_BASE 0x4009040
#define CAMERA_READY_BIT_CLEARING_EDGE_REGISTER 0
#define CAMERA_READY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CAMERA_READY_CAPTURE 0
#define CAMERA_READY_DATA_WIDTH 1
#define CAMERA_READY_DO_TEST_BENCH_WIRING 0
#define CAMERA_READY_DRIVEN_SIM_VALUE 0
#define CAMERA_READY_EDGE_TYPE "NONE"
#define CAMERA_READY_FREQ 50000000
#define CAMERA_READY_HAS_IN 0
#define CAMERA_READY_HAS_OUT 1
#define CAMERA_READY_HAS_TRI 0
#define CAMERA_READY_IRQ -1
#define CAMERA_READY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CAMERA_READY_IRQ_TYPE "NONE"
#define CAMERA_READY_NAME "/dev/CAMERA_READY"
#define CAMERA_READY_RESET_VALUE 0
#define CAMERA_READY_SPAN 16
#define CAMERA_READY_TYPE "altera_avalon_pio"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x04008820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1b
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1b
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x04008820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1b
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1b
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SPI
#define __ALTERA_NIOS2_GEN2
#define __ALTERA_UP_AVALON_ACCELEROMETER_SPI


/*
 * GPIO3 configuration
 *
 */

#define ALT_MODULE_CLASS_GPIO3 altera_avalon_pio
#define GPIO3_BASE 0x40090e0
#define GPIO3_BIT_CLEARING_EDGE_REGISTER 0
#define GPIO3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define GPIO3_CAPTURE 0
#define GPIO3_DATA_WIDTH 1
#define GPIO3_DO_TEST_BENCH_WIRING 0
#define GPIO3_DRIVEN_SIM_VALUE 0
#define GPIO3_EDGE_TYPE "NONE"
#define GPIO3_FREQ 50000000
#define GPIO3_HAS_IN 0
#define GPIO3_HAS_OUT 1
#define GPIO3_HAS_TRI 0
#define GPIO3_IRQ -1
#define GPIO3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define GPIO3_IRQ_TYPE "NONE"
#define GPIO3_NAME "/dev/GPIO3"
#define GPIO3_RESET_VALUE 0
#define GPIO3_SPAN 16
#define GPIO3_TYPE "altera_avalon_pio"


/*
 * IMG_ADDR_DRAM configuration
 *
 */

#define ALT_MODULE_CLASS_IMG_ADDR_DRAM altera_avalon_pio
#define IMG_ADDR_DRAM_BASE 0x4009030
#define IMG_ADDR_DRAM_BIT_CLEARING_EDGE_REGISTER 0
#define IMG_ADDR_DRAM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define IMG_ADDR_DRAM_CAPTURE 0
#define IMG_ADDR_DRAM_DATA_WIDTH 17
#define IMG_ADDR_DRAM_DO_TEST_BENCH_WIRING 0
#define IMG_ADDR_DRAM_DRIVEN_SIM_VALUE 0
#define IMG_ADDR_DRAM_EDGE_TYPE "NONE"
#define IMG_ADDR_DRAM_FREQ 50000000
#define IMG_ADDR_DRAM_HAS_IN 0
#define IMG_ADDR_DRAM_HAS_OUT 1
#define IMG_ADDR_DRAM_HAS_TRI 0
#define IMG_ADDR_DRAM_IRQ -1
#define IMG_ADDR_DRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define IMG_ADDR_DRAM_IRQ_TYPE "NONE"
#define IMG_ADDR_DRAM_NAME "/dev/IMG_ADDR_DRAM"
#define IMG_ADDR_DRAM_RESET_VALUE 0
#define IMG_ADDR_DRAM_SPAN 16
#define IMG_ADDR_DRAM_TYPE "altera_avalon_pio"


/*
 * LEDR configuration
 *
 */

#define ALT_MODULE_CLASS_LEDR altera_avalon_pio
#define LEDR_BASE 0x40090f0
#define LEDR_BIT_CLEARING_EDGE_REGISTER 0
#define LEDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDR_CAPTURE 0
#define LEDR_DATA_WIDTH 10
#define LEDR_DO_TEST_BENCH_WIRING 0
#define LEDR_DRIVEN_SIM_VALUE 0
#define LEDR_EDGE_TYPE "NONE"
#define LEDR_FREQ 50000000
#define LEDR_HAS_IN 0
#define LEDR_HAS_OUT 1
#define LEDR_HAS_TRI 0
#define LEDR_IRQ -1
#define LEDR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDR_IRQ_TYPE "NONE"
#define LEDR_NAME "/dev/LEDR"
#define LEDR_RESET_VALUE 0
#define LEDR_SPAN 16
#define LEDR_TYPE "altera_avalon_pio"


/*
 * PB_SW_1 configuration
 *
 */

#define ALT_MODULE_CLASS_PB_SW_1 altera_avalon_pio
#define PB_SW_1_BASE 0x40090d0
#define PB_SW_1_BIT_CLEARING_EDGE_REGISTER 0
#define PB_SW_1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PB_SW_1_CAPTURE 0
#define PB_SW_1_DATA_WIDTH 1
#define PB_SW_1_DO_TEST_BENCH_WIRING 0
#define PB_SW_1_DRIVEN_SIM_VALUE 0
#define PB_SW_1_EDGE_TYPE "NONE"
#define PB_SW_1_FREQ 50000000
#define PB_SW_1_HAS_IN 1
#define PB_SW_1_HAS_OUT 0
#define PB_SW_1_HAS_TRI 0
#define PB_SW_1_IRQ -1
#define PB_SW_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PB_SW_1_IRQ_TYPE "NONE"
#define PB_SW_1_NAME "/dev/PB_SW_1"
#define PB_SW_1_RESET_VALUE 0
#define PB_SW_1_SPAN 16
#define PB_SW_1_TYPE "altera_avalon_pio"


/*
 * PB_SW_2 configuration
 *
 */

#define ALT_MODULE_CLASS_PB_SW_2 altera_avalon_pio
#define PB_SW_2_BASE 0x40090c0
#define PB_SW_2_BIT_CLEARING_EDGE_REGISTER 0
#define PB_SW_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PB_SW_2_CAPTURE 0
#define PB_SW_2_DATA_WIDTH 1
#define PB_SW_2_DO_TEST_BENCH_WIRING 0
#define PB_SW_2_DRIVEN_SIM_VALUE 0
#define PB_SW_2_EDGE_TYPE "NONE"
#define PB_SW_2_FREQ 50000000
#define PB_SW_2_HAS_IN 1
#define PB_SW_2_HAS_OUT 0
#define PB_SW_2_HAS_TRI 0
#define PB_SW_2_IRQ -1
#define PB_SW_2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PB_SW_2_IRQ_TYPE "NONE"
#define PB_SW_2_NAME "/dev/PB_SW_2"
#define PB_SW_2_RESET_VALUE 0
#define PB_SW_2_SPAN 16
#define PB_SW_2_TYPE "altera_avalon_pio"


/*
 * PIXEL_DATA configuration
 *
 */

#define ALT_MODULE_CLASS_PIXEL_DATA altera_avalon_pio
#define PIXEL_DATA_BASE 0x4009050
#define PIXEL_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define PIXEL_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIXEL_DATA_CAPTURE 0
#define PIXEL_DATA_DATA_WIDTH 4
#define PIXEL_DATA_DO_TEST_BENCH_WIRING 0
#define PIXEL_DATA_DRIVEN_SIM_VALUE 0
#define PIXEL_DATA_EDGE_TYPE "NONE"
#define PIXEL_DATA_FREQ 50000000
#define PIXEL_DATA_HAS_IN 0
#define PIXEL_DATA_HAS_OUT 1
#define PIXEL_DATA_HAS_TRI 0
#define PIXEL_DATA_IRQ -1
#define PIXEL_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIXEL_DATA_IRQ_TYPE "NONE"
#define PIXEL_DATA_NAME "/dev/PIXEL_DATA"
#define PIXEL_DATA_RESET_VALUE 0
#define PIXEL_DATA_SPAN 16
#define PIXEL_DATA_TYPE "altera_avalon_pio"


/*
 * SDRAM configuration
 *
 */

#define ALT_MODULE_CLASS_SDRAM altera_avalon_new_sdram_controller
#define SDRAM_BASE 0x0
#define SDRAM_CAS_LATENCY 3
#define SDRAM_CONTENTS_INFO
#define SDRAM_INIT_NOP_DELAY 0.0
#define SDRAM_INIT_REFRESH_COMMANDS 2
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_IS_INITIALIZED 1
#define SDRAM_NAME "/dev/SDRAM"
#define SDRAM_POWERUP_DELAY 100.0
#define SDRAM_REFRESH_PERIOD 15.625
#define SDRAM_REGISTER_DATA_IN 1
#define SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_SDRAM_BANK_WIDTH 2
#define SDRAM_SDRAM_COL_WIDTH 10
#define SDRAM_SDRAM_DATA_WIDTH 16
#define SDRAM_SDRAM_NUM_BANKS 4
#define SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_SDRAM_ROW_WIDTH 13
#define SDRAM_SHARED_DATA 0
#define SDRAM_SIM_MODEL_BASE 0
#define SDRAM_SPAN 67108864
#define SDRAM_STARVATION_INDICATOR 0
#define SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_T_AC 5.5
#define SDRAM_T_MRD 3
#define SDRAM_T_RCD 20.0
#define SDRAM_T_RFC 70.0
#define SDRAM_T_RP 20.0
#define SDRAM_T_WR 14.0


/*
 * SEVEN_SEG_0 configuration
 *
 */

#define ALT_MODULE_CLASS_SEVEN_SEG_0 altera_avalon_pio
#define SEVEN_SEG_0_BASE 0x40090b0
#define SEVEN_SEG_0_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEG_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEG_0_CAPTURE 0
#define SEVEN_SEG_0_DATA_WIDTH 8
#define SEVEN_SEG_0_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEG_0_DRIVEN_SIM_VALUE 0
#define SEVEN_SEG_0_EDGE_TYPE "NONE"
#define SEVEN_SEG_0_FREQ 50000000
#define SEVEN_SEG_0_HAS_IN 0
#define SEVEN_SEG_0_HAS_OUT 1
#define SEVEN_SEG_0_HAS_TRI 0
#define SEVEN_SEG_0_IRQ -1
#define SEVEN_SEG_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEVEN_SEG_0_IRQ_TYPE "NONE"
#define SEVEN_SEG_0_NAME "/dev/SEVEN_SEG_0"
#define SEVEN_SEG_0_RESET_VALUE 0
#define SEVEN_SEG_0_SPAN 16
#define SEVEN_SEG_0_TYPE "altera_avalon_pio"


/*
 * SEVEN_SEG_1 configuration
 *
 */

#define ALT_MODULE_CLASS_SEVEN_SEG_1 altera_avalon_pio
#define SEVEN_SEG_1_BASE 0x40090a0
#define SEVEN_SEG_1_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEG_1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEG_1_CAPTURE 0
#define SEVEN_SEG_1_DATA_WIDTH 8
#define SEVEN_SEG_1_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEG_1_DRIVEN_SIM_VALUE 0
#define SEVEN_SEG_1_EDGE_TYPE "NONE"
#define SEVEN_SEG_1_FREQ 50000000
#define SEVEN_SEG_1_HAS_IN 0
#define SEVEN_SEG_1_HAS_OUT 1
#define SEVEN_SEG_1_HAS_TRI 0
#define SEVEN_SEG_1_IRQ -1
#define SEVEN_SEG_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEVEN_SEG_1_IRQ_TYPE "NONE"
#define SEVEN_SEG_1_NAME "/dev/SEVEN_SEG_1"
#define SEVEN_SEG_1_RESET_VALUE 0
#define SEVEN_SEG_1_SPAN 16
#define SEVEN_SEG_1_TYPE "altera_avalon_pio"


/*
 * SEVEN_SEG_2 configuration
 *
 */

#define ALT_MODULE_CLASS_SEVEN_SEG_2 altera_avalon_pio
#define SEVEN_SEG_2_BASE 0x4009090
#define SEVEN_SEG_2_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEG_2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEG_2_CAPTURE 0
#define SEVEN_SEG_2_DATA_WIDTH 8
#define SEVEN_SEG_2_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEG_2_DRIVEN_SIM_VALUE 0
#define SEVEN_SEG_2_EDGE_TYPE "NONE"
#define SEVEN_SEG_2_FREQ 50000000
#define SEVEN_SEG_2_HAS_IN 0
#define SEVEN_SEG_2_HAS_OUT 1
#define SEVEN_SEG_2_HAS_TRI 0
#define SEVEN_SEG_2_IRQ -1
#define SEVEN_SEG_2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEVEN_SEG_2_IRQ_TYPE "NONE"
#define SEVEN_SEG_2_NAME "/dev/SEVEN_SEG_2"
#define SEVEN_SEG_2_RESET_VALUE 0
#define SEVEN_SEG_2_SPAN 16
#define SEVEN_SEG_2_TYPE "altera_avalon_pio"


/*
 * SEVEN_SEG_3 configuration
 *
 */

#define ALT_MODULE_CLASS_SEVEN_SEG_3 altera_avalon_pio
#define SEVEN_SEG_3_BASE 0x4009080
#define SEVEN_SEG_3_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEG_3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEG_3_CAPTURE 0
#define SEVEN_SEG_3_DATA_WIDTH 8
#define SEVEN_SEG_3_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEG_3_DRIVEN_SIM_VALUE 0
#define SEVEN_SEG_3_EDGE_TYPE "NONE"
#define SEVEN_SEG_3_FREQ 50000000
#define SEVEN_SEG_3_HAS_IN 0
#define SEVEN_SEG_3_HAS_OUT 1
#define SEVEN_SEG_3_HAS_TRI 0
#define SEVEN_SEG_3_IRQ -1
#define SEVEN_SEG_3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEVEN_SEG_3_IRQ_TYPE "NONE"
#define SEVEN_SEG_3_NAME "/dev/SEVEN_SEG_3"
#define SEVEN_SEG_3_RESET_VALUE 0
#define SEVEN_SEG_3_SPAN 16
#define SEVEN_SEG_3_TYPE "altera_avalon_pio"


/*
 * SEVEN_SEG_4 configuration
 *
 */

#define ALT_MODULE_CLASS_SEVEN_SEG_4 altera_avalon_pio
#define SEVEN_SEG_4_BASE 0x4009070
#define SEVEN_SEG_4_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEG_4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEG_4_CAPTURE 0
#define SEVEN_SEG_4_DATA_WIDTH 8
#define SEVEN_SEG_4_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEG_4_DRIVEN_SIM_VALUE 0
#define SEVEN_SEG_4_EDGE_TYPE "NONE"
#define SEVEN_SEG_4_FREQ 50000000
#define SEVEN_SEG_4_HAS_IN 0
#define SEVEN_SEG_4_HAS_OUT 1
#define SEVEN_SEG_4_HAS_TRI 0
#define SEVEN_SEG_4_IRQ -1
#define SEVEN_SEG_4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEVEN_SEG_4_IRQ_TYPE "NONE"
#define SEVEN_SEG_4_NAME "/dev/SEVEN_SEG_4"
#define SEVEN_SEG_4_RESET_VALUE 0
#define SEVEN_SEG_4_SPAN 16
#define SEVEN_SEG_4_TYPE "altera_avalon_pio"


/*
 * SEVEN_SEG_5 configuration
 *
 */

#define ALT_MODULE_CLASS_SEVEN_SEG_5 altera_avalon_pio
#define SEVEN_SEG_5_BASE 0x4009060
#define SEVEN_SEG_5_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEG_5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEG_5_CAPTURE 0
#define SEVEN_SEG_5_DATA_WIDTH 8
#define SEVEN_SEG_5_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEG_5_DRIVEN_SIM_VALUE 0
#define SEVEN_SEG_5_EDGE_TYPE "NONE"
#define SEVEN_SEG_5_FREQ 50000000
#define SEVEN_SEG_5_HAS_IN 0
#define SEVEN_SEG_5_HAS_OUT 1
#define SEVEN_SEG_5_HAS_TRI 0
#define SEVEN_SEG_5_IRQ -1
#define SEVEN_SEG_5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SEVEN_SEG_5_IRQ_TYPE "NONE"
#define SEVEN_SEG_5_NAME "/dev/SEVEN_SEG_5"
#define SEVEN_SEG_5_RESET_VALUE 0
#define SEVEN_SEG_5_SPAN 16
#define SEVEN_SEG_5_TYPE "altera_avalon_pio"


/*
 * SPI configuration
 *
 */

#define ALT_MODULE_CLASS_SPI altera_avalon_spi
#define SPI_BASE 0x4009000
#define SPI_CLOCKMULT 1
#define SPI_CLOCKPHASE 1
#define SPI_CLOCKPOLARITY 1
#define SPI_CLOCKUNITS "Hz"
#define SPI_DATABITS 8
#define SPI_DATAWIDTH 16
#define SPI_DELAYMULT "1.0E-9"
#define SPI_DELAYUNITS "ns"
#define SPI_EXTRADELAY 0
#define SPI_INSERT_SYNC 0
#define SPI_IRQ 2
#define SPI_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SPI_ISMASTER 1
#define SPI_LSBFIRST 0
#define SPI_NAME "/dev/SPI"
#define SPI_NUMSLAVES 2
#define SPI_PREFIX "spi_"
#define SPI_SPAN 32
#define SPI_SYNC_REG_DEPTH 2
#define SPI_TARGETCLOCK 5000000u
#define SPI_TARGETSSDELAY "0.0"
#define SPI_TYPE "altera_avalon_spi"


/*
 * SRAM configuration
 *
 */

#define ALT_MODULE_CLASS_SRAM altera_avalon_onchip_memory2
#define SRAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SRAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SRAM_BASE 0x4004000
#define SRAM_CONTENTS_INFO ""
#define SRAM_DUAL_PORT 0
#define SRAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define SRAM_INIT_CONTENTS_FILE "NIOS2_WEEK2_SRAM"
#define SRAM_INIT_MEM_CONTENT 0
#define SRAM_INSTANCE_ID "NONE"
#define SRAM_IRQ -1
#define SRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SRAM_NAME "/dev/SRAM"
#define SRAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SRAM_RAM_BLOCK_TYPE "AUTO"
#define SRAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define SRAM_SINGLE_CLOCK_OP 0
#define SRAM_SIZE_MULTIPLE 1
#define SRAM_SIZE_VALUE 16384
#define SRAM_SPAN 16384
#define SRAM_TYPE "altera_avalon_onchip_memory2"
#define SRAM_WRITABLE 1


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_IRQ_BASE NULL
#define ALT_LEGACY_INTERRUPT_API_PRESENT
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x4009108
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x4009108
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x4009108
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "NIOS2_WEEK2"


/*
 * WRITE_ENABLE configuration
 *
 */

#define ALT_MODULE_CLASS_WRITE_ENABLE altera_avalon_pio
#define WRITE_ENABLE_BASE 0x4009020
#define WRITE_ENABLE_BIT_CLEARING_EDGE_REGISTER 0
#define WRITE_ENABLE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define WRITE_ENABLE_CAPTURE 0
#define WRITE_ENABLE_DATA_WIDTH 1
#define WRITE_ENABLE_DO_TEST_BENCH_WIRING 0
#define WRITE_ENABLE_DRIVEN_SIM_VALUE 0
#define WRITE_ENABLE_EDGE_TYPE "NONE"
#define WRITE_ENABLE_FREQ 50000000
#define WRITE_ENABLE_HAS_IN 0
#define WRITE_ENABLE_HAS_OUT 1
#define WRITE_ENABLE_HAS_TRI 0
#define WRITE_ENABLE_IRQ -1
#define WRITE_ENABLE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define WRITE_ENABLE_IRQ_TYPE "NONE"
#define WRITE_ENABLE_NAME "/dev/WRITE_ENABLE"
#define WRITE_ENABLE_RESET_VALUE 0
#define WRITE_ENABLE_SPAN 16
#define WRITE_ENABLE_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x4009108
#define JTAG_UART_0_IRQ 1
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8

#endif /* __SYSTEM_H_ */
